name: Build And Deploy

on:
  push:
    branches: [ "main" ]
    tags:
      - new-release


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: subosito/flutter-action@v2
      - run: |
          flutter clean
          flutter pub get
      - name: Build apk
        uses: subosito/flutter-action@v2
      - run: flutter build apk --split-per-abi
      - name: Deploy to App Center
        uses: avocaddo/AppCenter-Github-Action@v1.0.2
        with:
          token: ${{secrets.APP_CENTER_ACCESS_TOKEN}}
          command: appcenter distribute release -f android/app/build/outputs/flutter-apk/app-armeabi-v7a-release.apk -g Collaborators --app Miraç Altun/flutterboy20-dictionary_app
        