name: Code Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  codePush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: subosito/flutter-action@v2
      - run: |
          flutter clean
          flutter pub get
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release --app Miraç Altun/flutterboy20-dictionary_app -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}