name: Build And Deploy

on:
  push:
    branches: [ "main" ]
    tags:
      - new-release


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: subosito/flutter-action@v2
      - run: |
          flutter clean
          flutter pub get
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react --app Miraç Altun/flutterboy20-dictionary_app -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}